# Generated by Django 3.2.8 on 2021-11-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=3, max_digits=20)),
                ('caducidad', models.CharField(max_length=20)),
            ],
        ),
    ]
